### ISSUE TITLE
strcmp() expects parameter 1 to be string

### ISSUE THREAD

**Issue by plabong** [noris-network/mediawiki-extensions-sessionprovider-remoteuser#9] opened 2017-01-10 15:03 UTC
debian testing (stretch)
mediawiki 1.27.1
php 7.0.14
AuthRemoteuser: 1.3.2

When AuthRemoteuser is activated then the following error is thrown:

`PHP Warning:  strcmp() expects parameter 1 to be string, array given in <mw-path>/includes/user/User.php on line 5145`

**Comment by fnk** [comment] 2017-02-03 11:51
This sounds to me like the username does not get picked up, see #8 

Either way, i cannot reproduce this so i am closing this isssue.
If you can provide a whole stack trace for this error, i can reopen it.

In general i recommend updateing to mediawiki 1.28. We had lots of strange behaviour with 1.27.x and other extensions.

**Closed as completed by fnk** 2017-02-03 11:51 UTC
